// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2yQs3IWXM36ADBRSpysvybyXHcrh93A',
    appId: '1:697679348230:web:4d5e12ec02276b9db77987',
    messagingSenderId: '697679348230',
    projectId: 'trashtrack-7962b',
    authDomain: 'trashtrack-7962b.firebaseapp.com',
    storageBucket: 'trashtrack-7962b.appspot.com',
    measurementId: 'G-5QQTRWVRXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2W3f-K4p0wMSXFF9OaZZQIbkKO2Cmcg',
    appId: '1:697679348230:android:ac7e45cc63492e70b77987',
    messagingSenderId: '697679348230',
    projectId: 'trashtrack-7962b',
    storageBucket: 'trashtrack-7962b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMWCYgbIhdXkPdc9N7v-Dj7txdfXbWfKc',
    appId: '1:697679348230:ios:99049618fec40046b77987',
    messagingSenderId: '697679348230',
    projectId: 'trashtrack-7962b',
    storageBucket: 'trashtrack-7962b.appspot.com',
    iosClientId: '697679348230-k78ea96qdupld7l0q5o7hphg54jrnh7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMWCYgbIhdXkPdc9N7v-Dj7txdfXbWfKc',
    appId: '1:697679348230:ios:7652b81ee491268bb77987',
    messagingSenderId: '697679348230',
    projectId: 'trashtrack-7962b',
    storageBucket: 'trashtrack-7962b.appspot.com',
    iosClientId: '697679348230-olskcsjvmffgbabt7alj1feadte76g6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashTrackApp.RunnerTests',
  );
}
